"""Base wrapper-side runtime patches for Onyx containers.

Loaded automatically by Python when this directory is on PYTHONPATH.
"""

from __future__ import annotations

from wrapper_env_patches import apply_code_interpreter_network_description_patches
from wrapper_env_patches import apply_coding_agent_final_answer_fallback_patch
from wrapper_env_patches import apply_firecrawl_wait_for_patch
from wrapper_env_patches import apply_internal_search_context_patches
from wrapper_env_patches import apply_llm_max_tokens_override_patch
from wrapper_env_patches import apply_open_url_char_limit_patches
from wrapper_env_patches import apply_preserve_tool_results_patch
from wrapper_env_patches import apply_reasoning_content_preservation_patch

apply_llm_max_tokens_override_patch()
apply_open_url_char_limit_patches()
apply_internal_search_context_patches()
apply_firecrawl_wait_for_patch()
apply_code_interpreter_network_description_patches()
apply_reasoning_content_preservation_patch()
apply_coding_agent_final_answer_fallback_patch()
apply_preserve_tool_results_patch()
