"""Base wrapper-side runtime patches for Onyx containers.

Loaded automatically by Python when this directory is on PYTHONPATH.
"""

from __future__ import annotations

from wrapper_env_patches import apply_code_interpreter_network_description_patches
from wrapper_env_patches import apply_coding_agent_final_answer_fallback_patch
from wrapper_env_patches import apply_coding_agent_repo_download_limit_patch
from wrapper_env_patches import apply_deep_research_chat_agent_tools_patch
from wrapper_env_patches import apply_internal_search_context_patches
from wrapper_env_patches import apply_llm_max_tokens_override_patch
from wrapper_env_patches import apply_native_reasoning_detection_override_patch
from wrapper_env_patches import apply_open_url_char_limit_patches
from wrapper_env_patches import apply_playwright_helper_proxy_patch
from wrapper_env_patches import apply_preserve_tool_results_patch
from wrapper_env_patches import apply_reasoning_content_preservation_patch
from wrapper_env_patches import apply_reasoning_mode_trace_patch
from wrapper_env_patches import apply_vllm_glm_auto_tool_choice_patch

apply_llm_max_tokens_override_patch()
apply_open_url_char_limit_patches()
apply_coding_agent_repo_download_limit_patch()
apply_playwright_helper_proxy_patch()
apply_internal_search_context_patches()
apply_native_reasoning_detection_override_patch()
apply_code_interpreter_network_description_patches()
apply_vllm_glm_auto_tool_choice_patch()
apply_reasoning_mode_trace_patch()
apply_deep_research_chat_agent_tools_patch()
apply_reasoning_content_preservation_patch()
apply_coding_agent_final_answer_fallback_patch()
apply_preserve_tool_results_patch()
