use_default_settings:
  engines:
    remove:
      - google
      - google images
      - google news
      - google videos
      - brave
      - brave.images
      - brave.videos
      - brave.news
      - duckduckgo
      - duckduckgo images
      - duckduckgo videos
      - duckduckgo news
      - duckduckgo web
      - startpage
      - startpage news
      - startpage images

search:
  formats:
    - html
    - json

server:
  secret_key: "DCIc01DEbGttdLWtTPdISq8fHrb99l"

outgoing:
  request_timeout: 6.0

engines:
  - name: google2
    engine: google2
    shortcut: go2
    timeout: 60.0
    disabled: false
    enable_http: true

  - name: brave2
    engine: brave2
    shortcut: br2
    timeout: 60.0
    disabled: false
    enable_http: true

  - name: duckduckgo2
    engine: duckduckgo2
    shortcut: ddg2
    timeout: 60.0
    disabled: false
    enable_http: true

  - name: startpage2
    engine: startpage2
    shortcut: sp2
    timeout: 60.0
    disabled: false
    enable_http: true
